#!/bin/dash

#                      _                                      
#  _ __ ___  _ __ __ _| |_ ___   ___  ___ _ __ ___  ___ _ __  
# | '__/ _ \| '__/ _` | __/ _ \ / __|/ __| '__/ _ \/ _ \ '_ \ 
# | | | (_) | | | (_| | ||  __/ \__ \ (__| | |  __/  __/ | | |
# |_|  \___/|_|  \__,_|\__\___| |___/\___|_|  \___|\___|_| |_|
# this script use dmenu to choose 
# screen rotation

# define variables
PROMPT="rotate screen output:"
FONT="CaskaydiaCove Nerd FONT Mono:pixelsize=22"

# choose rotation method
item=$(echo "normal\nupside down\n+90 degree\n-90 degree" |dmenu -l 4 -p "$PROMPT" -fn "$FONT")

# rotate
if [ -n "$item" ]
then
    case $item in
        "normal") xrandr --output HDMI-A-0 --rotate normal;;
        "upside down") xrandr --output HDMI-A-0 --rotate inverted;;
        "+90 degree") xrandr --output HDMI-A-0 --rotate right;;
        "-90 degree") xrandr --output HDMI-A-0 --rotate left;;
    esac
fi
