#!/usr/bin/dash
#      _             _                             _ _       
#   __| |_ __ ___   | |_ _ __ __ _ _ __  ___  __ _| | |_ ___ 
#  / _` | '_ ` _ \  | __| '__/ _` | '_ \/ __|/ _` | | __/ _ \
# | (_| | | | | | | | |_| | | (_| | | | \__ \ (_| | | ||  __/
#  \__,_|_| |_| |_|  \__|_|  \__,_|_| |_|___/\__,_|_|\__\___|
#
# this script used to translate word or sentense
# via dmenu
# "translate" is a local shell script.

# define variables
PROMPT="translate:"
FONT="CaskaydiaCove Nerd FONT Mono:pixelsize=22"

# translate what we typed
echo 	|dmenu -p "$PROMPT" -fn "$FONT" \
	|xargs --null translate
