#!/bin/dash

#       _                                         _                      
#   ___| |__   __ _ _ __   __ _  ___  __   _____ | |_   _ _ __ ___   ___ 
#  / __| '_ \ / _` | '_ \ / _` |/ _ \ \ \ / / _ \| | | | | '_ ` _ \ / _ \
# | (__| | | | (_| | | | | (_| |  __/  \ V / (_) | | |_| | | | | | |  __/
#  \___|_| |_|\__,_|_| |_|\__, |\___|   \_/ \___/|_|\__,_|_| |_| |_|\___|
#                         |___/                                          


OPERATE=${1:-""}
CHANGE=${2:-0}
[ $CHANGE = 0 ] && exit 0

ifmute=$(pamixer --get-mute)
current=$(pamixer --get-volume)
volume=$(expr $current $OPERATE $CHANGE)

[ $ifmute = "true" ] && notify-send -u critical "Notice: sound has been muted" || ( \
	pamixer --set-volume $volume && \
	notify-send -h string:frcolor:#d5cecb \
		    -h int:value:$volume \
		    -h string:x-dunst-stack-tag:volume \
		    "sound volume: ${volume}%" \
		    -t 1000 \
)
