#!/bin/bash
#                  _                                                 
#   ___ __ _ _ __ | |_ _   _ _ __ ___   ___  ___ _ __ ___  ___ _ __  
#  / __/ _` | '_ \| __| | | | '__/ _ \ / __|/ __| '__/ _ \/ _ \ '_ \ 
# | (_| (_| | |_) | |_| |_| | | |  __/ \__ \ (__| | |  __/  __/ | | |
#  \___\__,_| .__/ \__|\__,_|_|  \___| |___/\___|_|  \___|\___|_| |_|
#           |_|                                                      

# define variables
LOCATION="$HOME/public/pictures/capture/"
FILE_NAME=$(date +%Y%m%d%H%M%S).png
FILE_FORMAT="png"

# use ffcast to take screen shot
ffcast $FILE_FORMAT ${LOCATION}${FILE_NAME} && \
    dunstify -t 3000 "screen capture in $LOCATION"
