#!/bin/sh

#  _                    _                        _       
# | |_ ___   __ _  __ _| | ___   _ __ ___  _   _| |_ ___ 
# | __/ _ \ / _` |/ _` | |/ _ \ | '_ ` _ \| | | | __/ _ \
# | || (_) | (_| | (_| | |  __/ | | | | | | |_| | ||  __/
#  \__\___/ \__, |\__, |_|\___| |_| |_| |_|\__,_|\__\___|
#           |___/ |___/                                  


pamixer --toggle-mute && \
	[ `pamixer --get-volume-human` = 'muted' ] && \
	dunstify -u critical 'Notice: voice has been muted!'
